name: Rename .txt File with Timestamp

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  rename-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: Rename .txt file
        run: |
          FILE=$(ls *.txt)
          if [ -f "$FILE" ]; then
            mv "$FILE" "${FILE%.txt}-${{ env.TIMESTAMP }}.txt"
          else
            echo "No .txt file found!"
          fi

      - name: Debug token and repository info
        run: |
          # Log the repository for verification
          echo "Repository: ${{ github.repository }}"
          
          # Check if the token exists, without logging the actual token
          if [ -n "${{ secrets.PAT_TOKEN }}" ]; then
            echo "Token is available."
          else
            echo "Token is missing!"
          fi
          
          # Log partial token (for debugging)
          echo "Partial token: ${TOKEN:0:4}****"

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Renamed .txt file to include timestamp"
          echo "Pushing changes..."
          
          # Log the full URL for verification
          echo "Git URL: https://x-access-token:****@github.com/${{ github.repository }}.git"
          
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
